repos:
    - repo: https://github.com/golangci/golangci-lint.git
      rev: v1.39.0
      hooks:
          - id: golangci-lint

customer_docker:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/customer/service/Dockerfile --destination $CI_REGISTRY_IMAGE/customerservice:$CI_COMMIT_TAG