@startuml
skinparam componentStyle rectangle
component customer
component catalog
component stock
component order
component payment
component shipment
component supplier

() Zahlungsdienstleister
() Zulieferer
() Versanddienstleister

database customdata [
    Kundennummer
    Name
    Adresse
]

database catalogdata [
    Artikelnummer
    Artikelname
]

database stockdata [
    Artikelnummer
    Artikelbestand
]

database orderdata [
    Bestellungsnummer
    Artikelnummern
    Anzahl Artikel
    Kundennummer
    Preis
    Flag retoure
]

order --> payment
shipment --> stock
shipment <-- payment
supplier --> stock
order <-- customer
supplier --> catalog
order --> catalog
customer ..> customdata : hat
catalog ..> catalogdata : hat
stock ..> stockdata : hat
order ...> orderdata : hat

payment <-- Zahlungsdienstleister
supplier --> Zulieferer
shipment --> Versanddienstleister

@enduml