version: "3"
services:

  # Dependencies
  redis:
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  nats:
    image: nats

  # App
  logger-service:
    build:
      context: .
      dockerfile: logger/Dockerfile
    image: logger
    depends_on:
      - nats 

  customer-service:
    image: gitlab.lrz.de:5005/vss/semester/ob-21ws/blatt-2/blatt2-gruppe14/customerservice
    depends_on:
      - redis
      - nats 
      - logger-service

  payment-service:
    build:
      context: .
      dockerfile: payment/service/Dockerfile
    image: payment
    depends_on:
      - redis
      - nats
      - logger-service 
          
  catalog-service:
    build:
      context: .
      dockerfile: catalog/service/Dockerfile
    image: catalog
    depends_on:
      - redis
      - nats
      - logger-service 
      - stock-service
    
  stock-service:
    build:
      context: .
      dockerfile: stock/service/Dockerfile
    image: stock
    depends_on:
      - redis
      - nats 
      - logger-service 

  order-service:
    build:
      context: .
      dockerfile: order/service/Dockerfile
    image: order
    depends_on:
      - redis
      - nats
      - logger-service 
      - payment-service
      - catalog-service
      - shipment-service

  shipment-service:
    build:
      context: .
      dockerfile: shipment/service/Dockerfile
    image: shipment
    depends_on:
      - redis
      - nats 
      - logger-service 
      - stock-service

  supplier-service:
    build:
      context: .
      dockerfile: supplier/service/Dockerfile
    image: supplier
    depends_on:
      - redis
      - nats 
      - logger-service 
      - stock-service

  client:
    build:
      context: .
      dockerfile: client/service/Dockerfile
    image: client
    depends_on:
      - redis
      - nats
      - logger-service 
      - customer-service
      - catalog-service
      - order-service
      - payment-service
      - stock-service
      - shipment-service
      - supplier-service


